### ISSUE TITLE
Too many tags

### ISSUE THREAD

**Issue by charafweb** [samclarke/SCEditor-MyBB#18]
Hi Sam,

The editor adds a lot of tags:

BBCode Tags added for a title:

[align=center][ltr][color=#111111][size=small][font=Verdana,Arial,Helvetica,sans-serif][size=xx-large]Qu’est-ce qu’une problématique[font=Arial,sans-serif] ?[/font][/size][/font][/size][/color][/ltr][/align]

And HTML tags for the same title:

![too_many_html](https://f.cloud.github.com/assets/2504989/74054/004a3ef8-6076-11e2-8a00-be7f136f8c41.png)

Here is just one Title! you can imagine how many html tags (and thereby how much size will take in database) will be there in a long article. And it will be very difficult to edit such a post in source mode (using bbcode)...

I edit many posts in a small forum using your editor, and I noticed that  that the size of database raised by 100% (twice the original size!) 

Thank you

**Comment by samclarke** [comment]
It doesn't store the HTML tags, it converts them to and from BBCode. Unfortunately there isn't really anyway to tell which BBCodes you wanted and which you didn't.

There are plans to remove obvious things like [size=small][anothertag][size=xx-large]only large text[/size][/anothertag][/size] but again it has to be sure [size=small] will have no effect on the other tags otherwise it will lose formatting.
